package:
  format-version: "1.0.0"
  name: "wireless_miwi"
  type: "package"
  status: "production"
  required: false
  version: "1.1.0"

  dependencies:
    - name: "csp"
      type: "package"
      version: "3.18.5"
    - name: "bsp"
      type: "package"
      version: "3.19.0"
    - name: "core"
      type: "package"
      version: "3.13.3"
    - name: "CMSIS-FreeRTOS"
      type: "package"
      version: "10.5.1"
    - name: "crypto"
      type: "package"
      version: "3.8.1"
    - name: "wolfssl"
      type: "package"
      version: "5.4.0"
    - name: "wireless_pic32cxbz_wbz"
      type: "package"
      version: "1.3.0"
    - name: "wireless_15_4_phy"
      type: "package"
      version: "1.2.0" 
